# Generated by Django 4.1.13 on 2026-06-06 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=200, verbose_name='标题')),
                ('content', models.TextField(verbose_name='正文')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='covers/', verbose_name='封面图')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='阅读量')),
                ('likes', models.PositiveIntegerField(default=0, verbose_name='点赞数')),
                ('is_published', models.BooleanField(default=True, verbose_name='是否发布')),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
                'db_table': 'articles_article',
                'ordering': ['-created_at'],
            },
        ),
    ]
