# Generated by Django 4.1.13 on 2026-06-07 08:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Festival',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='节日名称')),
                ('month', models.IntegerField(verbose_name='月份')),
                ('day', models.IntegerField(verbose_name='日期')),
                ('bonus_points', models.IntegerField(default=10, verbose_name='赠送积分')),
            ],
            options={
                'db_table': 'points_festival',
            },
        ),
        migrations.CreateModel(
            name='UserPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.IntegerField(default=0, verbose_name='积分余额')),
                ('total_earned', models.IntegerField(default=0, verbose_name='累计获得积分')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='points', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户积分',
                'verbose_name_plural': '用户积分',
                'db_table': 'points_user_points',
            },
        ),
        migrations.CreateModel(
            name='SignInRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sign_date', models.DateField(default=django.utils.timezone.now, verbose_name='签到日期')),
                ('month', models.CharField(help_text='格式 YYYY-MM', max_length=7, verbose_name='年月')),
                ('points_gained', models.IntegerField(default=1, verbose_name='获得积分')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sign_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'points_sign_in_record',
            },
        ),
        migrations.CreateModel(
            name='PointsTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='变动数量（正为获得，负为消耗）')),
                ('transaction_type', models.CharField(choices=[('sign_in', '每日签到'), ('sign_bonus', '满月奖励'), ('festival', '节日福利'), ('publish_article', '发布文章'), ('receive_like', '收到点赞'), ('download_pay', '下载支付'), ('download_income', '下载收入'), ('admin_adjust', '管理员调整')], max_length=30, verbose_name='类型')),
                ('related_object_id', models.CharField(blank=True, help_text='如文章ID、签到记录ID', max_length=50, verbose_name='关联对象ID')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '积分流水',
                'verbose_name_plural': '积分流水',
                'db_table': 'points_points_transaction',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='signinrecord',
            index=models.Index(fields=['user', 'month'], name='points_sign_user_id_f31337_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='signinrecord',
            unique_together={('user', 'sign_date')},
        ),
    ]
