# Generated by Django 4.1.13 on 2026-06-16 01:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('points', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointstransaction',
            name='transaction_type',
            field=models.CharField(choices=[('sign_in', '每日签到'), ('sign_bonus', '满月奖励'), ('festival', '节日福利'), ('publish_article', '发布文章'), ('receive_like', '收到点赞'), ('download_pay', '下载支付'), ('download_income', '下载收入')], max_length=30, verbose_name='类型'),
        ),
        migrations.CreateModel(
            name='UserFestivalReceiveLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receive_date', models.DateField(auto_now_add=True, verbose_name='领取时间')),
                ('festival', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='points.festival')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '节日积分领取记录',
                'db_table': 'User_festival_receiveLog',
                'unique_together': {('user', 'festival', 'receive_date')},
            },
        ),
    ]
